"""nexa-bidkit: day-ahead and intraday auction bid generation for European power markets."""

from nexa_bidkit.curves import (
    aggregate_by_price,
    clip_curve,
    constant_curve,
    empty_curve,
    filter_zero_volume,
    from_dataframe,
    from_dict_list,
    from_series_pair,
    get_curve_summary,
    linear_curve,
    merge_curves,
    scale_curve,
    to_dataframe,
    validate_dataframe_schema,
)
from nexa_bidkit.types import (
    BiddingZone,
    BidStatus,
    BidType,
    CurveType,
    DeliveryPeriod,
    Direction,
    MTUDuration,
    MTUInterval,
    Price,
    PriceQuantityCurve,
    PriceQuantityStep,
    Volume,
)

__all__ = [
    # Curve construction and manipulation
    "aggregate_by_price",
    "clip_curve",
    "constant_curve",
    "empty_curve",
    "filter_zero_volume",
    "from_dataframe",
    "from_dict_list",
    "from_series_pair",
    "get_curve_summary",
    "linear_curve",
    "merge_curves",
    "scale_curve",
    "to_dataframe",
    "validate_dataframe_schema",
    # Types
    "BiddingZone",
    "BidStatus",
    "BidType",
    "CurveType",
    "DeliveryPeriod",
    "Direction",
    "MTUDuration",
    "MTUInterval",
    "Price",
    "PriceQuantityCurve",
    "PriceQuantityStep",
    "Volume",
]
